module.exports = {
  "mainSidebar": [
    "documentation-overview",
    {
      "type": "category",
      "label": "Introduction",
      "items": [
        "introduction/overview",
        "introduction/installation",
        "introduction/quick-start"
      ]
    },
    {
      "type": "category",
      "label": "How-To",
      "items": [
        {
          "type": "category",
          "label": "Traverse Graphs",
          "items": [
            "how-to/traverse-basic"
          ]
        },
        {
          "type": "category",
          "label": "GraphQL",
          "items": [
            "how-to/graphql-basic",
            "how-to/graphql-manual",
            "how-to/graphql-simplegql"
          ]
        },
        {
          "type": "category",
          "label": "Import From File",
          "items": [
            "how-to/import-csv",
            "how-to/imgui-csv",
            "how-to/import-graph-formats"
          ]
        },
        "how-to/add-to-a-graph",
        "how-to/share-graphs",
        "how-to/use-zef-networkx",
        "how-to/manage-login",
        "reacting-to-graph-changes",
        {
          "type": "category",
          "label": "ZefFX",
          "items": [
            "clipboard",
            "reading-and-writing-files",
            "http",
            "websocket"
          ]
        },
        "introduction-to-zef-db",
        "using-zef-fx"
      ]
    },
    {
      "type": "category",
      "label": "Explanations",
      "items": [
        "explanations/privileges",
        "explanations/blob-structure",
        {
          "type": "category",
          "label": "Wish",
          "items": [
            "wish"
          ]
        },
        {
          "type": "category",
          "label": "ZefFX",
          "items": [
            "wish"
          ]
        },
        "introduction-to-logic-types",
        "zef-ops-two-levels-of-laziness",
        {
          "type": "category",
          "label": "FlatGraph",
          "items": [
            "merging"
          ]
        },
        {
          "type": "category",
          "label": "Concepts",
          "items": [
            "zef-ref",
            "reference-types",
            "reference-frame-programming",
            "semantic-diffing",
            "graph-slice",
            "atoms"
          ]
        },
        "data-first-vs-data-last-languages-where-python-stands",
        "unifying-streams-and-dbs",
        "zef-design-aspirations",
        "low-level-graph-data-layout",
        "introduction-to-zef-fx",
        {
          "type": "category",
          "label": "ZefDB",
          "items": [
            "relational-or-graph"
          ]
        },
        {
          "type": "category",
          "label": "Code Search",
          "items": [
            "finding-zef-ops"
          ]
        },
        "why-we-built-zef",
        {
          "type": "category",
          "label": "Graphs",
          "items": [
            "graph-instructions",
            "graph-instructions"
          ]
        }
      ]
    },
    {
      "type": "category",
      "label": "Tutorials",
      "items": [
        "tutorials/basic/employee-database",
        "tutorials/budgeter/budgeter",
        {
          "type": "category",
          "label": "Advent of Code",
          "items": [
            "2021-day-5",
            "2021-day-1",
            "2021-day-3",
            "2021-day-6"
          ]
        },
        "zef-ops-syntax-gym"
      ]
    },
    {
      "type": "category",
      "label": "Reference",
      "items": [
        "reference/glossary",
        "reference/cheatsheet-comprehensive",
        "reference/zef-ops"
      ]
    },
    {
      "type": "category",
      "label": "Configuration",
      "items": [
        "configuration-auth",
        "configuration-config",
        "configuration-messages",
        "configuration-env",
        "configuration-client-state"
      ]
    },
    {
      "type": "doc",
      "label": "FAQ",
      "id": "faq"
    },
    "documentation-overview"
  ],
  "developerSidebar": [
    {
      "type": "category",
      "label": "Internal",
      "link": {
        "type": "generated-index",
        "title": "Internal guides",
        "description": "Autogenerated index page for internal",
        "slug": "/internal"
      },
      "items": [
        "internal/updating-global-tokens",
        "internal/importing-submodules"
      ]
    }
  ]
}